# Generated by Django 3.1 on 2020-08-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0008_auto_20200814_1102"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note", name="body", field=models.TextField(verbose_name="body"),
        ),
    ]
