# Generated by Django 3.1 on 2020-08-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0009_auto_20200815_1132"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.SmallIntegerField(
                choices=[
                    (-2, "lowest"),
                    (-1, "low"),
                    (0, "normal"),
                    (1, "high"),
                    (2, "highest"),
                ],
                default=0,
                verbose_name="priority",
            ),
        ),
    ]
