# Generated by Django 3.1 on 2020-08-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_auto_20200819_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmembership',
            name='expires_at',
            field=models.DateField(blank=True, null=True, verbose_name='expires at'),
        ),
    ]
