# Generated by Django 3.1 on 2020-08-19 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0013_auto_20200819_0615"),
    ]

    operations = [
        migrations.RemoveField(model_name="project", name="owner",),
        migrations.AlterField(
            model_name="projectmembership",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="membership",
                to="tasks.project",
            ),
        ),
        migrations.AlterField(
            model_name="projectmembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="membership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
