# Generated by Django 3.1 on 2020-08-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0018_task_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_archived",
            field=models.BooleanField(default=False, verbose_name="archived"),
        ),
    ]
