# Generated by Django 3.1 on 2020-08-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0019_task_is_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_archived",
            field=models.BooleanField(default=False, verbose_name="archived"),
        ),
    ]
