name: Verify and test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Check formatting with Black
      run: |
        black --check .
    - name: Lint with Pylint
      run: |
        pylint auth minitask tasks
    - name: Run tests
      run: |
        python manage.py test
